import { useRef, useEffect } from "react";
import type { TranscriptEntry } from "../../types/game";
import styles from "./TranscriptPanel.module.css";

interface TranscriptPanelProps {
  entries: TranscriptEntry[];
}

const KIND_LABEL: Record<TranscriptEntry["kind"], string> = {
  kickoff: "DM",
  player: "PC",
  npc: "NPC",
  system: "SYS",
};

export function TranscriptPanel({ entries }: TranscriptPanelProps) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [entries]);

  if (entries.length === 0) {
    return (
      <div className={`${styles.panel} ${styles.empty}`}>
        <p className={styles.emptyHint}>Press <strong>Init</strong> to start a new adventure.</p>
      </div>
    );
  }

  return (
    <div className={styles.panel}>
      <div className={styles.scroll}>
        {entries.map((entry) => (
          <div
            key={entry.id}
            className={`${styles.entry} ${styles[`kind_${entry.kind}`]}`}
          >
            <div className={styles.entryHeader}>
              <span className={styles.kindBadge}>
                {KIND_LABEL[entry.kind]}
              </span>
              <span className={styles.actorId}>{entry.actorId}</span>
              {entry.source === "intent_agent" && (
                <span className={styles.aiBadge} title="Action generated by intent agent">
                  AI
                </span>
              )}
              <span className={`${styles.statusBadge} ${styles[`status_${entry.status}`]}`}>
                {entry.status}
              </span>
            </div>

            {entry.action && (
              <p className={styles.actionText}>"{entry.action}"</p>
            )}

            {entry.reasoning && (
              <p className={styles.reasoning}>{entry.reasoning}</p>
            )}

            <p className={styles.ruling}>{entry.ruling}</p>
          </div>
        ))}
        <div ref={bottomRef} />
      </div>
    </div>
  );
}
